export interface ConfigSetting {
  option: string;
  preference: string;
  value: string;
  description: string;
}

const checklist: ConfigSetting[] = [
  {
    option: 'Block active mixed content',
    preference: 'security.mixed_content.block_active_content',
    value: 'true',
    description: '',
  },
  {
    option: 'Block display mixed content',
    preference: 'security.mixed_content.block_display_content',
    value: 'true',
    description: '',
  },
  {
    option: 'Disable Addon Cache',
    preference: 'extensions.getAddons.cache.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Addon Updates',
    preference: 'extensions.update.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Battery API',
    preference: 'dom.battery.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Browser Pings',
    preference: 'browser.send_pings',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Browsing and Download history',
    preference: 'places.history.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable CSS visited links',
    preference: 'layout.css.visited_links_enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Cache (disk)',
    preference: 'browser.cache.disk.enable',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Cache (memory)',
    preference: 'browser.cache.memory.enable',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Clipboard Events',
    preference: 'dom.event.clipboardevents.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Content Menu Events',
    preference: 'dom.event.contextmenu.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Device Sensors',
    preference: 'device.sensors.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable DNS prefetch',
    preference: 'network.dns.disablePrefetch',
    value: 'true',
    description: '',
  },
  {
    option: 'Disable DOM storage',
    preference: 'dom.storage.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable DRM',
    preference: 'media.eme.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Geolocation',
    preference: 'geo.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Geolocation 2',
    preference: 'geo.wifi.uri',
    value: 'Leave empty',
    description: '',
  },
  {
    option: 'Disable offline cache',
    preference: 'browser.cache.offline.enable',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable PDF.js',
    preference: 'pdfjs.disabled',
    value: 'true',
    description: '',
  },
  {
    option: 'Disable Pocket',
    preference: 'extensions.pocket.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Resource Timing API',
    preference: 'dom.enable_resource_timing',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Search suggestions',
    preference: 'browser.search.suggest.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Search Updates',
    preference: 'browser.search.update',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable Speculative Pre-Connections',
    preference: 'network.http.speculative-parallel-limit',
    value: '0',
    description: '',
  },
  {
    option: 'Disable SSL False Start',
    preference: 'security.ssl.enable_false_start',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable SSL Session Identifiers',
    preference: 'security.ssl.disable_session_identifiers',
    value: 'true',
    description: '',
  },
  {
    option: 'Disable TLS 0-RTT',
    preference: 'security.tls.enable_0rtt_data',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable TTR (Trusted Recursive Resolver)',
    preference: 'network.trr.mode',
    value: '5',
    description: '',
  },
  {
    option: 'Disable WebGL',
    preference: 'webgl.disabled',
    value: 'true',
    description: '',
  },
  {
    option: 'Disable Web Beacons',
    preference: 'beacon.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Enable clear offline apps on shutdown',
    preference: 'privacy.clearOnShutdown.offlineApps',
    value: 'true',
    description: '',
  },
  {
    option: 'Enable social tracking protection (FF70+)',
    preference: 'privacy.trackingprotection.socialtracking.enabled',
    value: 'true',
    description: '',
  },
  {
    option: 'Limit detectable fonts',
    preference: 'browser.display.use_document_fonts',
    value: '0',
    description: '',
  },
  {
    option: 'Limit max tabs undo',
    preference: 'browser.sessionstore.max_tabs_undo',
    value: '0',
    description: '',
  },
  {
    option: 'Use click to play for plugins',
    preference: 'plugins.click_to_play',
    value: 'true',
    description: '',
  },
  {
    option: 'Disable data submission',
    preference: 'datareporting.policy.dataSubmissionEnabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable safe browsing downloads check',
    preference: 'browser.safebrowsing.downloads.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable safe browsing downloads check 2',
    preference: 'browser.safebrowsing.downloads.remote.block_potentially_unwanted',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable safe browsing downloads check 3',
    preference: 'browser.safebrowsing.downloads.remote.block_uncommon',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable safe browsing downloads check 4',
    preference: 'browser.safebrowsing.downloads.remote.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable safe browsing malware check',
    preference: 'browser.safebrowsing.malware.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable safe browsing phishing check',
    preference: 'browser.safebrowsing.phishing.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable health report uploads',
    preference: 'datareporting.healthreport.uploadEnabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable crash report',
    preference: 'browser.tabs.crashReporting.sendReport',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable telemetry pings',
    preference: 'toolkit.telemetry.server',
    value: 'Leave empty',
    description: '',
  },
  {
    option: 'Disable telemetry report',
    preference: 'toolkit.telemetry.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable telemetry report 2',
    preference: 'toolkit.telemetry.unified',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable user media enumeration',
    preference: 'media.navigator.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Disable user media enumeration 2',
    preference: 'media.peerconnection.enabled',
    value: 'false',
    description: '',
  },
  {
    option: 'Set session privacy level',
    preference: 'browser.sessionstore.privacy_level',
    value: '2',
    description: '',
  },
];
