export interface ChecklistItem {
  name: string;
  preference: string;
  value: string;
  description: string;
  causeBreak: boolean;
}

export const Checklist: ChecklistItem[] = [
  {
    name: 'Block active mixed content',
    preference: 'security.mixed_content.block_active_content',
    value: 'true',
    description: 'Blocks non-HTTPS active mixed content (scripts, iframes, CSS, AJAX/fetch requests) from being loaded on an HTTPS page',
    causeBreak: true,
  },
  {
    name: 'Block display mixed content',
    preference: 'security.mixed_content.block_display_content',
    value: 'true',
    description: 'Blocks non-HTTPS passive mixed content (images, audio, video) from being loaded on an HTTPS page',
    causeBreak: true,
  },
  {
    name: 'Disable Addon Cache',
    preference: 'extensions.getAddons.cache.enabled',
    value: 'false',
    description: 'Prevent updating addon metadata',
    causeBreak: false,
  },
  {
    name: 'Disable Addon Updates',
    preference: 'extensions.update.enabled',
    value: 'false',
    description: 'Prevent checking for addon updates.',
    causeBreak: false,
  },
  {
    name: 'Disable Battery API',
    preference: 'dom.battery.enabled',
    value: 'false',
    description: 'Disable Battery API. Can be used to track users.',
    causeBreak: false,
  },
  {
    name: 'Disable Browsing and Download history',
    preference: 'places.history.enabled',
    value: 'false',
    description: 'Disable Browsing and Download history',
    causeBreak: false,
  },
  {
    name: 'Disable Cache (disk)',
    preference: 'browser.cache.disk.enable',
    value: 'false',
    description: 'Prevent caching data on disk',
    causeBreak: false,
  },
  {
    name: 'Disable Cache (memory)',
    preference: 'browser.cache.memory.enable',
    value: 'false',
    description: 'Prevent caching data in memory',
    causeBreak: false,
  },
  {
    name: 'Disable Clipboard Events',
    preference: 'dom.event.clipboardevents.enabled',
    value: 'false',
    description: 'Prevents websites from detecting when a user copies, pastes, or cuts data from a web page and what was selected.',
    causeBreak: true,
  },
  {
    name: 'Disable Content Menu Events',
    preference: 'dom.event.contextmenu.enabled',
    value: 'false',
    description: 'Disables website control over right click context menu. Shift + Right Click to override.',
    causeBreak: false,
  },
  {
    name: 'Disable Device Sensors',
    preference: 'device.sensors.enabled',
    value: 'false',
    description: 'Disable devices sensors (will break sites that need access to sensors)',
    causeBreak: true,
  },
  {
    name: 'Disable DNS prefetch',
    preference: 'network.dns.disablePrefetch',
    value: 'true',
    description:
      'Prevent Firefox from proactively performing DNS resolution on links that the user may choose to follow as well as URLs for items referenced by elements on a web page.',
    causeBreak: false,
  },
  {
    name: 'Disable DOM storage',
    preference: 'dom.storage.enabled',
    value: 'false',
    description: 'Prevent sites from storing data (session storage and local storage).',
    causeBreak: true,
  },
  {
    name: 'Disable DRM',
    preference: 'media.eme.enabled',
    value: 'false',
    description: 'Disable DRM. Will cause issues with sites like Spotify and Netflix.',
    causeBreak: true,
  },
  {
    name: 'Disable Geolocation',
    preference: 'geo.enabled',
    value: 'false',
    description: 'Disable geolocation feature. Will break sites that request location.',
    causeBreak: false,
  },
  {
    name: 'Disable Geolocation 2',
    preference: 'geo.wifi.uri',
    value: 'Leave empty',
    description: `Remove Firefox's geolocation provider.`,
    causeBreak: false,
  },
  {
    name: 'Disable IDN support',
    preference: 'network.IDN_show_punycode',
    value: 'true',
    description: 'Always show raw punycode version of internationalized domain names. Phishing risk; for example http://www.аррӏе.com/ is shown as http://xn--80ak6aa92e.com.',
    causeBreak: false,
  },
  {
    name: 'Disable offline cache',
    preference: 'browser.cache.offline.enable',
    value: 'false',
    description: 'Prevent website data from being cached for offline use.',
    causeBreak: false,
  },
  {
    name: 'Disable PDF.js',
    preference: 'pdfjs.disabled',
    value: 'true',
    description: 'Prevent loading PDF inside browser.',
    causeBreak: false,
  },
  {
    name: 'Disable Pocket',
    preference: 'extensions.pocket.enabled',
    value: 'false',
    description: 'Potentially unwanted feature.',
    causeBreak: false,
  },
  {
    name: 'Disable Resource Timing API',
    preference: 'dom.enable_resource_timing',
    value: 'false',
    description: 'Resource Timing is a browser API to collect timing information for resources on a page. Can leak history, local network information, and possibly location.',
    causeBreak: false,
  },
  {
    name: 'Disable Search suggestions',
    preference: 'browser.search.suggest.enabled',
    value: 'false',
    description: 'Prevent search suggestions.',
    causeBreak: false,
  },
  {
    name: 'Disable Search Updates',
    preference: 'browser.search.update',
    value: 'false',
    description: 'Prevent Firefox from updating search engines.',
    causeBreak: false,
  },
  {
    name: 'Disable Speculative Pre-Connections',
    preference: 'network.http.speculative-parallel-limit',
    value: '0',
    description: 'Prevent Firefox from proactively fetching resources when an element is hovered or interacted with.',
    causeBreak: false,
  },
  {
    name: 'Disable SSL False Start',
    preference: 'security.ssl.enable_false_start',
    value: 'false',
    description: 'Prevent client from sending data before completing handshake to start session.',
    causeBreak: false,
  },
  {
    name: 'Disable SSL Session Identifiers',
    preference: 'security.ssl.disable_session_identifiers',
    value: 'true',
    description: 'Prevent tracking with TLS session resumption.',
    causeBreak: false,
  },
  {
    name: 'Disable TLS 0-RTT',
    preference: 'security.tls.enable_0rtt_data',
    value: 'false',
    description: `Zero Round Trip Time Resumption (0-RTT) is a feature that is new in TLS 1.3 that allows a client and server to negotiate a connection with fewer steps, allowing https websites to load more quickly. There are two problems with this. First, in order to do this you lose forward secrecy (generating a new key for every session and throwing away the key when the session is over). Secondly, 0-RTT requires special implementation in order to prevent replay attacks, which some web developers will certainly fail to protect from. - Credits https://github.com/privacytoolsIO/privacytools.io/issues/815#issue-428249054.`,
    causeBreak: false,
  },
  {
    name: 'Disable TTR (Trusted Recursive Resolver)',
    preference: 'network.trr.mode',
    value: '5',
    description: 'DNS-over-HTTPS bypasses hosts and uses Cloudflare/Google. DNS settings should be managed by the user instead.',
    causeBreak: false,
  },
  {
    name: 'Disable WebGL',
    preference: 'webgl.disabled',
    value: 'true',
    description: 'Disable WebGL (will cause issues with web games).',
    causeBreak: true,
  },
  {
    name: 'Disable Web Beacons',
    preference: 'beacon.enabled',
    value: 'false',
    description: 'Disable web beacons.',
    causeBreak: false,
  },
  {
    name: 'Enable clear offline apps on shutdown',
    preference: 'privacy.clearOnShutdown.offlineApps',
    value: 'true',
    description: 'Clear offline website data on shutdown.',
    causeBreak: false,
  },
  {
    name: 'Enable social tracking protection',
    preference: 'privacy.trackingprotection.socialtracking.enabled',
    value: 'true',
    description: 'Enable social tracking protection.',
    causeBreak: false,
  },
  {
    name: 'Limit detectable fonts',
    preference: 'browser.display.use_document_fonts',
    value: '0',
    description: 'Reduces installed fonts uniqueness. May cause issues with font icons.',
    causeBreak: true,
  },
  {
    name: 'Limit max tabs undo',
    preference: 'browser.sessionstore.max_tabs_undo',
    value: '0',
    description: 'Closed tabs are stored temporarily at Menu -> History -> Recently Closed Tabs regardless if Firefox is set to not remember history.',
    causeBreak: false,
  },
  {
    name: 'Use click to play for plugins',
    preference: 'plugins.click_to_play',
    value: 'true',
    description: 'Prevent plugins from automatically running when loading a page.',
    causeBreak: false,
  },
  {
    name: 'Disable data submission',
    preference: 'datareporting.policy.dataSubmissionEnabled',
    value: 'false',
    description: 'Disables data submission to Mozilla.',
    causeBreak: false,
  },
  {
    name: 'Disable safe browsing downloads check',
    preference: 'browser.safebrowsing.downloads.enabled',
    value: 'false',
    description: 'Disable safety check for downloaded files.',
    causeBreak: false,
  },
  {
    name: 'Disable safe browsing downloads check 2',
    preference: 'browser.safebrowsing.downloads.remote.block_potentially_unwanted',
    value: 'false',
    description: 'Disable safety check for potentially unwanted downloaded files.',
    causeBreak: false,
  },
  {
    name: 'Disable safe browsing downloads check 3',
    preference: 'browser.safebrowsing.downloads.remote.block_uncommon',
    value: 'false',
    description: 'Disable safety check for uncommon downloaded files.',
    causeBreak: false,
  },
  {
    name: 'Disable safe browsing downloads check 4',
    preference: 'browser.safebrowsing.downloads.remote.enabled',
    value: 'false',
    description: 'Disable checking binaries not in local lists by Google.',
    causeBreak: false,
  },
  {
    name: 'Disable safe browsing malware check',
    preference: 'browser.safebrowsing.malware.enabled',
    value: 'false',
    description: 'Prevents querying Google for safe browsing malware list.',
    causeBreak: false,
  },
  {
    name: 'Disable safe browsing phishing check',
    preference: 'browser.safebrowsing.phishing.enabled',
    value: 'false',
    description: 'Prevents querying Google for safe browsing phishing list.',
    causeBreak: false,
  },
  {
    name: 'Disable health report uploads',
    preference: 'datareporting.healthreport.uploadEnabled',
    value: 'false',
    description: 'Disable sending Health Report to Mozilla.',
    causeBreak: false,
  },
  {
    name: 'Disable crash report',
    preference: 'browser.tabs.crashReporting.sendReport',
    value: 'false',
    description: 'Disable sending crash reports to Mozilla.',
    causeBreak: false,
  },
  {
    name: 'Disable telemetry pings',
    preference: 'toolkit.telemetry.server',
    value: 'Leave empty',
    description: 'The telemetry server used if telemetry is enabled.',
    causeBreak: false,
  },
  {
    name: 'Disable telemetry report',
    preference: 'toolkit.telemetry.enabled',
    value: 'false',
    description: 'Disables telemetry.',
    causeBreak: false,
  },
  {
    name: 'Disable telemetry report 2',
    preference: 'toolkit.telemetry.unified',
    value: 'false',
    description: 'Disable telemetry from being enabled (overrides toolkit.telemetry.enabled).',
    causeBreak: false,
  },
  {
    name: 'Disable user media enumeration',
    preference: 'media.navigator.enabled',
    value: 'false',
    description: 'Prevents websites from listing available media devices (camera, microphone, etc).',
    causeBreak: true,
  },
  {
    name: 'Set session privacy level',
    preference: 'browser.sessionstore.privacy_level',
    value: '2',
    description: 'Setting session privacy level to 2 prevents Firefox from storing contents of forms, scrollbar positions, cookies, and POST data for restoring a session.',
    causeBreak: false,
  },
];
