export const CHANGE_PROFILE = 'CHANGE_PROFILE';
export const TOGGLE_CHAMELEON = 'TOGGLE_CHAMELEON';
export const TOGGLE_NOTIFICATIONS = 'TOGGLE_NOTIFICATIONS';
export const TOGGLE_THEME = 'TOGGLE_THEME';
